### ISSUE TITLE
On Windows a cmdline box is shown alogn the main window

### ISSUE THREAD

**Issue by marcelmiguel** [asticode/go-astilectron-demo#22] opened 2018-02-22 11:34 UTC
Is it possible not to show the cmdline box when openning the app?
Is it possible to open the window on a secondary screen?

**Comment by asticode** [comment] 2018-02-22 12:44
@marcelmiguel is this the same issue: https://github.com/asticode/go-astilectron/issues/18 ?

**Comment by marcelmiguel** [comment] 2018-02-22 14:36
It can be. The problem is that the terminal box is shown as long as the GUI.
Executing "astilectron_bundler -v" shows go build is executed with "-H windowsgui", that looks correct, I'm trying other options of go build, but none of them work.

**Comment by asticode** [comment] 2018-02-23 09:57
yeah the `windowsgui` ldflag usually do the trick. Which version of go and windows are you using?

**Comment by marcelmiguel** [comment] 2018-02-23 11:08
W10 & Go 1.10

**Comment by deranjer** [comment] 2018-02-27 01:23
Same exact setup here, same exact issue. go1.10 windows/amd64

**Comment by asticode** [comment] 2018-02-27 09:09
Have you tested W10 + Go 1.9 to see whether this is an issue brought by Go 1.10?

**Comment by asticode** [comment] 2018-03-31 12:00
Could you guys test on Go 1.10.1 ? I've tested it with Windows 10 and it's working properly.

**Comment by asticode** [comment] 2018-04-18 08:00
hey guys, could you check out the last answer of [this issue](https://github.com/golang/go/issues/24232) and see if that helps in any way?

**Comment by asticode** [comment] 2018-05-24 13:45
closing this issue as this is a duplicate of https://github.com/asticode/go-astilectron-bundler/issues/16

**Closed by asticode** 2018-05-24 13:45 UTC
Labels: bug
